AST-21265_PDF_REPORT
Checkmarx/ast-cli pull request #494
Opened 2023-01-20 06:38 UTC by igorlombacx

…port function

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](../docs/code_of_conduct.md). Please see the [contributing guidelines](../docs/contributing.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change.

### References

> Include supporting link to GitHub Issue/PR number

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).
- [ ] I have updated the CLI help for new/changed functionality in this PR (if applicable).
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

2023-01-24 09:31 UTC, tiagobcx requested changes

2023-01-24 16:56 UTC, igorlombacx commented on internal/commands/result.go
> +	summary.EnginesEnabled = strings.Split(strings.ToUpper(strings.Join(summary.EnginesEnabled, ",")), ",")
The API is case sensitive and would accept uppercase engines name

2023-01-25 10:37 UTC, tiagobcx approved these changes

2023-01-26 09:22 UTC, tiagobcx approved these changes

2023-01-26 14:13 UTC, merged