Fix bug# 22030 - Missing "SCA" results in sonar report
Checkmarx/ast-cli pull request #509
Opened 2023-03-04 07:48 UTC by margaritalm

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](../docs/code_of_conduct.md). Please see the [contributing guidelines](../docs/contributing.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change.

### References

> Include supporting link to GitHub Issue/PR number

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).
- [ ] I have updated the CLI help for new/changed functionality in this PR (if applicable).
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

2023-03-04 07:49 UTC, margaritalm commented
Hi, I created new branch and fixes after latest code review

2023-03-13 09:35 UTC, pedrompflopes commented on internal/commands/result.go
> +	auxLocation.FilePath = strings.TrimLeft(results.ScanResultData.Filename, "/")
Hi @margaritalm  I believe this scanREsultsData.Filename is not populated for SCA results. You need to use result.ScanResultData.ScaPackageCollection.Locations. Can you please check a SCA result ? 

Thanks

2023-03-13 09:36 UTC, pedrompflopes requested changes

2023-03-13 09:36 UTC, pedrompflopes commented on internal/commands/result.go
> +	auxLocation.FilePath = strings.TrimLeft(results.ScanResultData.Filename, "/")
We create this method for Sarif results : parseSarifResultsSca

2023-04-03 09:41 UTC, merged