Support more than 10k in summary results
Checkmarx/ast-cli pull request #579
Opened 2023-09-14 17:50 UTC by igorlombacx

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](../docs/code_of_conduct.md). Please see the [contributing guidelines](../docs/contributing.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change.

### References

> Include supporting link to GitHub Issue/PR number

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).
- [ ] I have updated the CLI help for new/changed functionality in this PR (if applicable).
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

2023-09-18 12:43 UTC, diogopcx requested changes

2023-09-18 12:43 UTC, diogopcx commented on internal/commands/result.go
> +	setNotAvailableNumberIfZero(summary, &summary.ScaIssues, scaType)
Can we add scaType to commonParams or use it if already existing?

2023-09-18 12:43 UTC, diogopcx commented on internal/commands/result.go
> +		"scan-ids": summary.ScanID,
Can we add a constants for this param?

2023-09-18 12:43 UTC, diogopcx commented on internal/commands/result.go
> +		logger.PrintIfVerbose(err.Error())
Is this print necessary? We are returning the error and the CLI should fail.

2023-09-18 12:43 UTC, diogopcx commented on internal/commands/result.go
> +		logger.PrintIfVerbose(errModel.Message)
Same as above.

2023-09-18 12:43 UTC, diogopcx commented on internal/commands/result.go
> +	if scanSummary == nil || len(scanSummary.ScansSummaries) > 1 {
We should maybe check if the length is not equal to 1, in case it comes empty line 445 will throw.

2023-09-18 12:43 UTC, diogopcx commented on internal/commands/result.go
> +	if isResultsNeeded {
If results are needed, are summaries also needed?

2023-09-18 12:43 UTC, diogopcx commented on internal/commands/result.go
> +	isResultsNeeded := verifyFormatsByReportList(reportList, printer.FormatJSON, printer.FormatSarif, printer.FormatSonar)
Consider having some static lists of summary report types and result report types in the printer package.

2023-09-18 12:43 UTC, diogopcx commented on internal/wrappers/results-http.go
> +// TODO il: review error responses
Please resolve this TODO

2023-09-18 13:10 UTC, igorlombacx commented on internal/commands/result.go
> +	if isResultsNeeded {
![image](https://github.com/Checkmarx/ast-cli/assets/114568996/01dd84e4-e422-40b1-9042-da433d44706e)
yes

2023-09-19 15:21 UTC, diogopcx approved these changes

2023-09-19 15:31 UTC, merged