Feature/ast 21466 critical severity
Checkmarx/ast-cli pull request #644
Opened 2024-01-22 16:26 UTC by tiagobcx

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](../docs/code_of_conduct.md). Please see the [contributing guidelines](../docs/contributing.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change.

### References

> Include supporting link to GitHub Issue/PR number

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).
- [ ] I have updated the CLI help for new/changed functionality in this PR (if applicable).
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

2024-01-23 12:20 UTC, hmmachadocx approved these changes

2024-05-28 10:10 UTC, OrShamirCM reviewed
Looks clean and good!
Please add critical severity to tests

2024-05-29 12:55 UTC, OrShamirCM reviewed
Please make sure to verify the reports too (Visablity not unit test)

2024-07-17 17:14 UTC, tamarleviCm requested changes
you don't cover the critical results with FF
now the cli always shows the critical severity in the console summary and in the reports
is it aligned with the pm?
if yes- did you check if the plugins not break if the results contain unexpected severity

2024-07-17 17:14 UTC, tamarleviCm commented on internal/commands/result.go
> +	infoCx:     "1.0",
you don't support the old way of scoring...

2024-07-18 09:27 UTC, tiagobcx commented on internal/commands/predicates.go
> +				--severity <CRITICAL|HIGH|MEDIUM|LOW|INFO>
This was the way it was decided, if the critical ff is enabled then we show the results otherwise we show it as N/A (not available) in the summary. So the reference for critical can be here. Until the plugins get updated it will only display the High, medium, low and info vulns. Once we do the changes there it will show everything.

2024-07-18 11:17 UTC, tamarleviCm commented on internal/wrappers/mock/results-mock.go
> +func (r ResultsMockWrapper) GetScanSummariesByScanIDS(params map[string]string) (*wrappers.ScanSummariesModel, *wrappers.WebError, error) {
what is this function? who calls it? i didn't see it in the code

2024-07-18 11:17 UTC, tamarleviCm commented on internal/commands/result_test.go
> +
add a test that check the critical results

2024-07-25 13:14 UTC, OrShamirCM commented on internal/commands/result.go
do we count api security critical severity? i saw that we found it in line 659, right?

2024-07-31 06:35 UTC, tamarleviCm approved these changes

2024-08-02 13:28 UTC, merged