Task # AST-31546
Checkmarx/ast-cli pull request #699
Opened 2024-04-07 14:55 UTC by margaritalm

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](../docs/code_of_conduct.md). Please see the [contributing guidelines](../docs/contributing.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change.

### References

> Include supporting link to GitHub Issue/PR number

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).
- [ ] I have updated the CLI help for new/changed functionality in this PR (if applicable).
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

2024-04-10 10:34 UTC, tamarleviCm reviewed
you have to add an unit tests and integration tests

2024-04-10 10:34 UTC, tamarleviCm commented on internal/commands/result.go
> +	glDependencyResult.Scan.Analyzer.Name = wrappers.AnalyzerScaID
duplicate line: glDependencyResult.Scan.Analyzer.Name = wrappers.AnalyzerScaID

2024-04-10 10:34 UTC, tamarleviCm commented on internal/commands/result.go
> +					DependencyLocationVersion: "",
you can delete these empty properties, I think it is the same if you don't provide them

2024-04-14 09:14 UTC, OrShamirCM commented on internal/commands/result.go
> +func convertCxResultToGlDependencyVulnerability(results *wrappers.ScanResultsCollection, glDependencyResult *wrappers.GlDependencyResultsCollection, summaryBaseURI string) {
Please create a differnet go file that contain only GL logic and call if from the results

2024-04-14 09:14 UTC, OrShamirCM requested changes
Please add unit tests for the gl new file and logic + integration test from results for "sad" + "happy" flow

2024-05-19 07:28 UTC, closed without merging